# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildPlatform: 'any cpu'
  buildConfiguration: 'Release'
steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '
  inputs:
    versionSpec: '$(Parameters.versionSpec)'
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    vstsFeed: 'a90b78c9-68ab-472c-9fc4-7ab9b4ac1d26'
    
- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
